var date= new Date()
console.log(date)
console.log(date.toDateString())
console.log(date.toTimeString())
console.log(date.toLocaleString())
console.log(date.toLocaleDateString())

console.log(date.getFullYear())
console.log(date.getDate())
console.log(date.getMonth())
console.log(date.getHours())